apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quotes-student-0
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: student-0
    server: 'https://kubernetes.default.svc'
  source:
    path: quotes-flask/helm/quotes-flask
    repoURL: 'https://github.com/eficode-academy/argocd-katas.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
